name: Release Workflow 📦

on:
  push:
    branches:
      - main
    paths:
      - 'pyproject.toml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x' # Specify the Python version.

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build

    - name: Get version
      id: get_version
      run: |
        echo "VERSION=v$(cat pyproject.toml | grep 'version = ' | sed 's/version = //g' | sed 's/"//g')" >> $GITHUB_ENV

    - name: Get latest commit messages
      id: get_commits
      run: |
        echo "COMMITS=$(git log --pretty=format:'%h - %s (%an)' $(git describe --tags --abbrev=0 @^)..@)" >> $GITHUB_ENV
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
      with:
        tag_name: ${{ env.VERSION }}
        release_name: Release ${{ env.VERSION }}
        body: |
          ### Description
          This release includes the following changes:
          ${{ env.COMMITS }}
        draft: false
        prerelease: false
  