name: Release Workflow 📦

on:
  push:
    branches:
      - main
    paths:
      - 'pyproject.toml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Extract version from pyproject.toml
        id: get_version
        run: echo "VERSION=$(cat pyproject.toml | grep version | cut -d'"' -f2)" >> $GITHUB_ENV

      - name: Check if tag exists
        id: check_tag
        run: |
          if git rev-parse "v${{ env.VERSION }}" >/dev/null 2>&1; then
            echo "::set-output name=exists::true"
          fi

      - name: Create Release
        if: steps.check_tag.outputs.exists != 'true'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        with:
          tag_name: ${{ env.VERSION }}
          release_name: Release ${{ env.VERSION }}
          draft: false
          prerelease: false

      - name: Push Changes
        if: steps.check_tag.outputs.exists != 'true'
        run: git push origin --tags
